version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/fintrack-service
    docker:
      - image: circleci/node:erbiumefault
    steps:
      - checkout
            - run:
          name: Install dependencies
          command: |
          
            npm install
            npm run build

