version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/fintrack-service
    docker:
            - image: circleci/node:erbiumefault
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test
